### ISSUE TITLE
Help!!!!!

### ISSUE THREAD

**Issue by Arobce** [wagle04/memes-from-reddit-api#1]
Please help the api only gives "Memes From Reddit App API" message and nothing else.

**Comment by wagle04** [comment]
wtf man

**Comment by wagle04** [comment]
The API was not well documented. 
here, to get top posts from reddit hit the website https://memes-from-reddit.herokuapp.com/redditposts with post request and body as like 

{
    "time": "day",
    "limit": 10,
    "subreddits": [
        "tinder",
        "funny",
        "dankmemes"
    ]
}

**Comment by Arobce** [comment]
I get a response 
`{
    "message": "The method is not allowed for the requested URL."
}`

**Comment by wagle04** [comment]
make a 'POST' HTTP request instead of 'GET'

**Comment by Arobce** [comment]
```
{
    "message": "Failed to decode JSON object: Expecting value: line 1 column 1 (char 0)"
}
```

**Comment by wagle04** [comment]
https://stackoverflow.com/questions/54908079/flask-api-failing-to-decode-json-data-error-message-failed-to-decode-json
